const homeElements = {
    inputSignupName:'[data-qa="signup-name"]',
    inputSignupEmail:'[data-qa="signup-email"]',
    btnSignup: '[data-qa="signup-button"]',
    inputLoginEmail: '[data-qa="login-email"]',
    inputLoginPassword: '[data-qa="login-password"]',
    checkTitle: '#id_gender1',
    inputNameSignup: '#name',
    inputPasswordSignup: '#password',
    selectDaySignup: 'select#days',
    selectMonthSignup: 'select#months',
    selectYearSignup: 'select#years',
    newsletterSignup: '#newsletter',
    firstNameSignup: '#first_name',
    lastNameSignup: '#last_name',
    companySignup: '#company',
    address1Signup: '#address1',
    address2Signup: '#address2',
    countrySignup: 'select#country',
    stateSignup: '#state',
    citySignup: '#city',
    zipCodeSignup: '#zipcode',
    mobileNumberSignup: '#mobile_number',
    btncreateAccountSignup: '[data-qa="create-account"]',
    btnContinueSignup: '[data-qa="continue-button"]',
    contactUsLink: 'a[href="/contact_us"]',
    inputNameContactUs: '[data-qa="name"]',
    inputEmailContactUs: '[data-qa="email"]',
    inputMessageContactUs: '[data-qa="message"]',
    selectFile: 'input[type="file"]',
    btnSubmitContactUs: '[data-qa="submit-button"]',
    statusContactUs: '.status',
    homePageLink: '.nav > :nth-child(1) > a',
    productLink: 'a[href="/products"]',
    searchProducts: '#search_product',
    btnSubmitSearch: '#submit_search',
    containerProducts: '.features_items',
};

export default homeElements;